apiVersion: v1
kind: Service
metadata:
  name: control-plane-sim
  namespace: default
  labels:
    app: control-plane-sim
spec:
  type: ClusterIP
  selector:
    app: control-plane-sim
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
